version: 2
updates:
    - package-ecosystem: 'npm'
      directory: '/'
      schedule:
          interval: 'daily'
      open-pull-requests-limit: 0 # begrens til security updates
    - package-ecosystem: 'npm'
      directory: '/server'
      schedule:
          interval: 'daily'
      open-pull-requests-limit: 0 # begrens til security updates
